sudo: required
services:
  - docker


  before_install:
    - docker build -t kellydouglass/readct-test -f ./front/Dockerfile.front.dev ./front

  script:
    - docker run kellydouglass/react-test npm test -- --coverage

  after_success:
    - docker build -t kellydouglass/multi-front ./front
    - docker build -t kellydouglass/multi-server ./server
    - docker build -t kellydouglass/multi-db .

    