sudo: required
services:
  - docker


  before_install:
    - docker build -t kellydouglass/readct-test -f ./front/Dockerfile.front.dev ./front

  script:
    - docker run kellydouglass/react-test npm test -- --coverage

  after_success:
    - docker build -t kellydouglass/practice-front ./front
    - docker build -t kellydouglass/practice-server ./server
    - docker build -t kellydouglass/practice-db .

