version: '3'
services: 
  db:
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    build:   
      context: .
      dockerfile: Dockerfile.db.dev
  
  front:
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile.front.dev
    ports:
      - "3000:80"
    volumes: 
    - /app/node_modules
    - ./front:/app
    - ./front/build:/usr/share/nginx/html
  
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.server.dev
    ports:
      - "4000:4000"
    volumes: 
    - /app/node_modules
    - ./server:/app
